data<-read.table("household_power_consumption.txt",col.names = c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"),sep = ";", skip = 66637, nrows = 2880,colClasses = "character")
data$Date <- as.Date(data$Date,format = "%d/%m/%Y")
data$Date <- paste(data$Date,data$Time)
data$Date <- as.POSIXct(data$Date)
par(mfrow = c(2,2),bg = "white")
with(data,{
  hist(as.numeric(data$Global_active_power),col = "red",xlab = "Global Active Power (kilowatts)",main = "Global Active Power")
  plot(data$Date,data$Global_active_power,ylab = "Global Active Power (kilowatts)",xlab="Time",type="l")
  plot(data$Date,data$Sub_metering_1,type = "l",xlab = "Time",ylab = "Energy sub metering",col = "black")
  lines(data$Date,data$Sub_metering_2,col = "red")
  lines(data$Date,data$Sub_metering_3,col = "blue")
  legend("topright",col = c("black","red","blue"),lty=1,legend = c("Sub metering 1","Sub metering 2","Sub metering 3"))
  plot(data$Date,data$Global_reactive_power,ylab = "Global Reactive Power",xlab="Time",type="l")
})
dev.copy(png,file="plot4.png")
dev.off()