data<-read.table("household_power_consumption.txt",col.names = c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"),sep = ";", skip = 66637, nrows = 2880,colClasses = "character")
data$Date <- as.Date(data$Date,format = "%d/%m/%Y")
data$Date <- paste(data$Date,data$Time)
data$Date <- as.POSIXct(data$Date)
par(bg = "white")
plot(data$Date,data$Global_active_power,ylab = "Global Active Power (kilowatts)",xlab="Time",type="l")
dev.copy(png,file = "plot2.png")
dev.off()